"""Data loading utilities for hyperspectral trust evidence.

The loaders support the selected Samson, Jasper Ridge and Urban MATLAB files,
and the HSI-NAC corrupted cubes generated by the local hsi_corruptions module.
All cubes are returned as H x W x B float32 arrays in [0, 1].
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np
from scipy.io import loadmat, savemat


@dataclass(frozen=True)
class DatasetSpec:
    name: str
    data_file: str
    image_key: str
    nrow_key: str
    ncol_key: str
    max_value_key: Optional[str] = None
    default_endmembers: int = 0


DATASET_SPECS = {
    "samson": DatasetSpec(
        name="samson",
        data_file="Samson/Data_Matlab/samson_1.mat",
        image_key="V",
        nrow_key="nRow",
        ncol_key="nCol",
        default_endmembers=3,
    ),
    "jasper": DatasetSpec(
        name="jasper",
        data_file="Jasper Ridge/jasperRidge2_R198.mat",
        image_key="Y",
        nrow_key="nRow",
        ncol_key="nCol",
        max_value_key="maxValue",
        default_endmembers=4,
    ),
    "urban": DatasetSpec(
        name="urban",
        data_file="Urban/Urban_R162.mat",
        image_key="Y",
        nrow_key="nRow",
        ncol_key="nCol",
        max_value_key="maxValue",
        default_endmembers=6,
    ),
}


def _scalar(mat: dict, key: str) -> int:
    return int(np.asarray(mat[key]).squeeze())


def normalize_cube(cube: np.ndarray) -> np.ndarray:
    cube = np.asarray(cube, dtype=np.float32)
    cube = np.nan_to_num(cube, nan=0.0, posinf=1.0, neginf=0.0)
    if cube.size and np.nanmax(cube) > 1.5:
        cube = cube / float(np.nanmax(cube))
    return np.clip(cube, 0.0, 1.0).astype(np.float32)


def load_reference_cube(data_root: str | Path, dataset: str) -> tuple[np.ndarray, dict]:
    dataset = dataset.lower()
    if dataset not in DATASET_SPECS:
        raise KeyError(f"Unknown dataset {dataset!r}. Available: {sorted(DATASET_SPECS)}")
    spec = DATASET_SPECS[dataset]
    path = Path(data_root) / spec.data_file
    if not path.exists():
        raise FileNotFoundError(path)

    mat = loadmat(path)
    arr = np.asarray(mat[spec.image_key], dtype=np.float32)
    nrow = _scalar(mat, spec.nrow_key)
    ncol = _scalar(mat, spec.ncol_key)

    if spec.max_value_key and spec.max_value_key in mat:
        max_value = float(np.asarray(mat[spec.max_value_key]).squeeze())
        if max_value > 0:
            arr = arr / max_value
    elif arr.size and np.nanmax(arr) > 1.5:
        arr = arr / float(np.nanmax(arr))

    if arr.ndim != 2:
        raise ValueError(f"Expected B x N matrix, got {arr.shape}")
    bands, pixels = arr.shape
    if pixels != nrow * ncol:
        raise ValueError(f"Pixel count mismatch: {pixels} != {nrow} * {ncol}")

    cube = np.stack([arr[b].reshape((nrow, ncol), order="F") for b in range(bands)], axis=-1)
    cube = normalize_cube(cube)
    meta = {
        "dataset": dataset,
        "source_path": str(path),
        "height": nrow,
        "width": ncol,
        "bands": bands,
        "default_endmembers": spec.default_endmembers,
    }
    return cube, meta


def load_cube_mat(path: str | Path) -> tuple[np.ndarray, dict]:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    mat = loadmat(path)
    if "cube" in mat:
        cube = np.asarray(mat["cube"], dtype=np.float32)
        if cube.ndim != 3:
            raise ValueError(f"Expected cube H x W x B, got {cube.shape}")
        cube = normalize_cube(cube)
        meta = {"source_path": str(path), "height": cube.shape[0], "width": cube.shape[1], "bands": cube.shape[2]}
        return cube, meta

    if "Y" not in mat:
        raise KeyError(f"{path} contains neither 'cube' nor 'Y'")
    arr = np.asarray(mat["Y"], dtype=np.float32)
    nrow = _scalar(mat, "nRow")
    ncol = _scalar(mat, "nCol")
    if arr.ndim != 2:
        raise ValueError(f"Expected Y as B x N matrix, got {arr.shape}")
    bands, pixels = arr.shape
    if pixels != nrow * ncol:
        raise ValueError(f"Pixel count mismatch: {pixels} != {nrow} * {ncol}")
    cube = np.stack([arr[b].reshape((nrow, ncol), order="F") for b in range(bands)], axis=-1)
    cube = normalize_cube(cube)
    meta = {"source_path": str(path), "height": nrow, "width": ncol, "bands": bands}
    return cube, meta


def cube_to_matrix(cube: np.ndarray) -> np.ndarray:
    """Return B x N matrix from H x W x B cube."""
    cube = normalize_cube(cube)
    return np.moveaxis(cube, -1, 0).reshape(cube.shape[-1], -1).astype(np.float32)


def save_map_npz(path: str | Path, **arrays: np.ndarray) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(path, **arrays)


def save_csv(path: str | Path, rows: list[dict], fieldnames: list[str]) -> None:
    import csv

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
